cbor.go, sign.go, sign1.go
Disallow CBOR tags for `Signature`, `SignMessage` and `Sign1Message`. The value of header maps can still have tags.
Fix #34
=> Disallow CBOR Tags

bench_test.go
This PR adds benchmarks for `Sign1Message` methods. These benchmarks will be useful later one to do memory and cpu profiling.
These are the results on my Windows laptop (use only for reference):
```bash
goos: windows
goarch: amd64
pkg: github.com/veraison/go-cose
cpu: Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
BenchmarkSign1Message_MarshalCBOR-12              666874              1791 ns/op             692 B/op         17 allocs/op
BenchmarkSign1Message_UnmarshalCBOR-12            368671              3303 ns/op            1592 B/op         28 allocs/op
BenchmarkSign1Message_Sign-12                     631834              1739 ns/op             668 B/op         16 allocs/op
BenchmarkSign1Message_Verify-12                   585108              1910 ns/op             668 B/op         16 …
```
=> add Sign1Message benchmarks

README.md, example_test.go, sign.go
=> Mark COSE Sign as experimental

README.md, algorithm.go, ecdsa.go, ed25519.go, headers.go, sign1.go, signer.go
This PR fixes several inconsistencies in our documentation found by the NCC Group.
@SteveLasker @shizhMSFT
Signed-off-by: qmuntal <qmuntaldiaz@microsoft.com>
=> Documentation cleanup

algorithm.go, algorithm_test.go
NCC Group reported a race condition in `RegisterAlgorithm`:
> The registration is performed through a global map. There is no mutex protection:
concurrent accesses from several distinct threads (“goroutines”) may lead to adverse
effects, including multiple registration of an algorithm, apparent removal of an existing
registration, or a panic due to an out-of-bounds memory access
is expected to apply its own locking to ensure that no other thread may access the
library (including for merely verifying a signature) while any thread is performing a
registration; however, this aspect is entirely undocumented
This PR fix the race condition.
@SteveLasker @shizhMSFT
=> Guard against race conditions in RegisterAlgorithm

ecdsa.go, ecdsa_test.go
Fixes #59
@SteveLasker @shizhMSFT
=> Use curve modulo instead of field size to calculate ECDSA signature length

README.md
The integer range is not render correctly due to it being inside a code block.
Fix it by moving the range out of the code block.
Signed-off-by: qmuntal <qmuntaldiaz@microsoft.com>
=> Fix integer range rendering

README.md
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>
=> Update readme with release info

headers.go, headers_test.go, sign.go, sign1.go, sign1_test.go, sign_test.go
The NCC Group found this issue:
> Partial IV: The ‘Initialization Vector’ and ‘Partial Initialization Vector’ parameters
MUST NOT both be present in the same security layer. (Section 3.1)
> The go-cose library does not provide any explicit support for these parameters. A user is
free to set them within a message, but go-cose will not prevent usage that contradicts the
above requirement.
To meet this requirement, we should ensure that the IV and Partial IV are not both present in the protected header when marshaling and unmarshaling it. This PR does that.
=> Ensure IV and Partial IV are not both present

rsa.go
Although `rs.alg.hashFunc()` never returns `false`, this PR makes it sound even if we have programming errors.
Fixes #75
=> Fail-safe check on RSA

example_test.go, headers.go, headers_test.go, sign1_test.go, sign_test.go
This PR validates that the [Common COSE Headers Parameters](https://datatracker.ietf.org/doc/html/rfc8152#section-3.1) have to correct type.
The change has been quite disruptive for our test cases, because we were using headers containing invalid parameters. Most of the test changes are related to fixing those tests.
This PR does not validate counter signature nor x509 common parameters, as go-cose currently does not expose the CBOR types which are contained in those parameters.
Fix #82
Signed-off-by: qmuntal <qmuntaldiaz@microsoft.com>
=> Validate generic headers

headers_test.go
#87 was merged without rerunning code coverage PR check added in #84, and now codecov is complaining because `main` does not meet the 89% coverage threshold. Let's fix it.
@SteveLasker @thomas-fossati @yogeshbdeshpande
=> Increase headers type validation coverage

README.md, reports/README.md
=> Enhance reports folder README.md and also top level README.md

algorithm.go, algorithm_test.go, bench_test.go, ecdsa.go, ecdsa_test.go, ed25519.go, ed25519_test.go, errors.go, fuzz_test.go, rsa.go, rsa_test.go, sign.go, sign1.go, sign1_test.go, sign_test.go, signer.go, signer_test.go, verifier.go
Resolves #100
Changes:
- `Sign()` in the `Signer` interface accepts message content instead of digest.
- `Verify()` in the `Verifier` interface accepts message content instead of digest.
- External algorithm registration is removed since signing and verification no longer require digest computation.
- Improved doc comments.
- Fixes tests.
=> refactor!: accept message content instead of digest for sign and verify

.github/workflows/ci.yml
Resolves #102
Note that `go.mod` is already at `go 1.18`.
Signed-off-by: Shiwei Zhang <shizh@microsoft.com>
=> chore: upgrade ci to go 1.18 and go 1.19

fuzz_test.go
This PR reduces the memory consumption of `FuzzSign1` by creating the necessary signers and verifiers before actually executing the fuzz target instead of creating a new set on every execution.
This fuzz test in particular is causing intermitent failures in an internal pipeline we (the Microsoft Go team) run nightly, and the error is always associated to the host killing the fuzzing execution due to an elevated memory consumption.
@thomas-fossati @shizhMSFT @yogeshbdeshpande
=> Reduce FuzzSign1 memory consumption

README.md
Replace cose-spec
from https://datatracker.ietf.org/doc/draft-ietf-cose-rfc8152bis-struct/ 
to https://datatracker.ietf.org/doc/rfc9052/
Closes #108
=> Update cose-spec from draft to RFC 9052

README.md
This PR updates the examples in the README.md to make it clear that the errors should be handled someway and also clarify hash function requirements.
Fixes #106
=> Improve README.md examples

cbor.go
=> Use cbor.SortCoreDeterministic for CBOR encoding

README.md
`VerifyP256` creates a new verifier for ES512
=> fix example in the readme

.github/workflows/ci.yml, testdata/sign1-sign-0000.json, verifier.go, verifier_test.go
Fix #115
Signed-off-by: Thomas Fossati <thomas.fossati@arm.com>
=> Check EC point is on curve at Verifier instantiation

errors.go, signer.go, verifier.go
Signed-off-by: Yogesh Deshpande <yogesh.deshpande@arm.com>
=> Correct return error code when key cannot be decoded

verifier_test.go
Fixes #118
Signed-off-by: Yogesh Deshpande <yogesh.deshpande@arm.com>
=> Add precise error conditions to verifier unit tests

cbor.go, cbor_test.go, sign.go, sign1.go, sign1_test.go, sign_test.go
=> fix: deterministic encode cose_sign / cose_sign1 sig_signature

CODEOWNERS
In the [February 10, 2023 go-cose community meeting](https://veraison.zulipchat.com/#narrow/stream/317999-go-cose-meetings/topic/Meeting.2010-02-2023), @roywill was nominated as a maintainer.
Per [veraison governance: Sub Project Maintainers](https://github.com/veraison/community/blob/main/GOVERNANCE.md#sub-project-maintainers)  a super majority LGTM of this PR affirms Roy joining the team.
NOTE: This PR is a delta from #133. 
Maintainers, please LGTM/merge #133 prior to merging this PR.
=> Add Roy Williams as a maintainer

.github/ISSUE_TEMPLATE/bug-or-issue.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yaml
Signed-off-by: Toddy Mladenov <toddysm@gmail.com>
=> Added issue templates

cbor_test.go, ecdsa_test.go, headers_test.go, sign1_test.go, sign_test.go, signer_test.go
Fixes #138 
Signed-off-by: Yogesh Deshpande <yogesh.deshpande@arm.com>
=> Enhance individual UT in go-cose library to handle specific errors

headers_test.go
Split the "iv and partial iv present" test case into separate "iv present" and "partial iv present" cases in headers test.
The issue is that validateHeaderParameters takes a map of extracted header parameters and range's over them, validating each one. Ranging over maps in Go does not guarantee a stable order.
This meant that ether the "IV" or the "Partial IV" parameter could be checked first in the "iv and partial iv present" test case, resulting in different errors being reported on different runs.
The test harness only allows specifying one expected error, so when the order of the header params map iteration switched, the actual and expected errors didn't match resulting in test failure.
One way to fix it would be sort map values before iterating over them, however that would be an …
=> Fix intermittent failures in headers tests

README.md, example_test.go, sign1.go, sign1_test.go
RFC8152 specifies that a single-signer token can be either tagged (COSE_Sign1_Tagged) or untagged (COSE_Sign1). Add support for parsing, and optionally generating, the untagged version.
The default behaviour is to still generated COSE_Sign1_Tagged.
=> Add untagged COSE_Sign1 support

.github/.codecov.yml, algorithm.go, algorithm_test.go, common.go, common_test.go, errors.go, headers.go, headers_test.go, key.go, key_test.go
Add support for  marshalling/unmarshalling `COSE_Key` structures, and using them for signing and verification. At the moment, only RFC8152 is implemented (OKP and EC2 signatures);  RFC8230 (RSASSA-PSS signatures) is NOT implemented.
=> Add `COSE_Key` support

go.mod
This release was published in error, as further work is required on COSE_Key.
This addresses https://github.com/veraison/go-cose/issues/152
=> Retract v1.2.0 release

sign1.go
=> fix: typo UnataggedSign1Message -> UntaggedSign1Message

algorithm.go, algorithm_test.go, common_test.go, errors.go, headers.go, key.go, key_test.go
This PR removes a bunch of methods added in #146 which, in my opinion, shouldn't have been added.
This is the list and the reasoning for removing them:
- Algorithm.UnmarshalCBOR: its sole purpose is to allow unmarshaling algorithms encoded as strings. We don't support any algorithm than can be references as a string, so this method always fail on such case. I would rather not add a code path for a thing that we don't support, just in case in the future we need to. It makes the code base bigger and more difficult to maintain.
- Algorithm.MarshalCBOR: it was only there as companion method for `Algorithm.UnmarshalCBOR`.
- KeyType.UnmarshalCBOR: same reasoning as in `Algorithm.UnmarshalCBOR`. Additionally, we should not error when the value is not supported by go-cose, as users might want to …
=> Remove unnecessary cbor marshal methods

key.go, key_test.go
This PR contains converts all COSE_Key-related tests to tabular tests, making those test more similar to the COSE_Sign related tests. Also, IMO, tabular tests make it easier to understand what is being tested, as they don't depend on reusing and mutating inputs but on explicit and clearly definid inputs and outputs.
There is just one behavior change in this PR: `NewEC2Key` and `NewOKPKey` return a nil key if the validation fails, together with the corresponding error. Returning nil objects when there is an error instead is more idiomatic and less error prone.
This will also facilitate testing the API redesign that I'll submit as part of #151.
=> Convert key tests to tabular tests

key.go, key_test.go
This PR adds the following features:
- Validate that the `x`, `y` and `d` parameters for OKP and EC2 keys have the right size.
- Recompute the  `x` and `y` for OKP and EC in case they are omitted, which is allowed by the COSE spec.
=> Validate key sizes and allow signing with empty public keys

README.md, algorithm.go, algorithm_test.go, ed25519.go, ed25519_test.go, fuzz_test.go, key.go, key_test.go, signer.go, signer_test.go, verifier.go, verifier_test.go
[RFC 88152 Section 8.2](https://www.rfc-editor.org/rfc/rfc8152#section-8.2) names the Edwards-Curve Digital Signature algorithm as `EdDSA`, but `go-cose` defines it as `const AlgorithmEd25519 = -8`. Our naming is misleading, the `-8` value can be used with other curves as well, e.g., `Ed448`, and the concept of an Ed25519 algorithm does not appear in the spec. We are mixing algorithms with curves.
We can't just rename the algorithm constant, it would break the API, but we can deprecate it and create a new one with a more accurate name: `AlgorithmEdDSA`,
=> Deprecate AlgorithmEd25519 and provide AlgorithmEdDSA instead

README.md, ecdsa.go, ecdsa_test.go, ed25519_test.go, example_test.go, rsa.go, rsa_test.go, signer.go, verifier.go
=> Make built-in types implement the new DigestSigner and DigestVerify interface

algorithm.go, algorithm_test.go, headers.go, key.go, key_test.go
This PR contain the following changes:
- Renamed `NewXKey` to `NewKeyX`, being X the key type. This form is more idiomatic.
- Removed the `Key` prefix from Key properties. It is go-ish to avoid prefixing the name of a property with the name of the struct.
- Rename `XInvalid` to `XReserved`, being X `KeyType`, `Curve`, `KeyOp` and `Algorithm`. This makes our API more similar to the COSE spec naming.
- Added some tests and spec pointers.
=> Consolidate API names related to Key

algorithm.go, algorithm_test.go, conformance_test.go, signer.go, signer_test.go, verifier.go, verifier_test.go
This PR replaces https://github.com/veraison/go-cose/pull/140. It closes https://github.com/veraison/go-cose/issues/141.
It only provides the constants for the algorithms. A `cose.Signer` or `cose.Verifier` needs to be implemented and provided from outside the package to use these algorithms. Using `NewSigner` and `NewVerifier` will return an error when called with one of these algorithms, because PKCS#1 v1.5 signing and verification aren't implemented in `go-cose` itself.
Example usage with external `mycose` package:
```golang
import (
"crypto/rand"
"github.com/veraison/go-cose"
"go.step.sm/crypto/keyutil"
"mycose"
)
func main(){
key, _ := keyutil.GenerateSigner("RSA", "", 2048)
cs := mycose.NewRS256Signer(key)  // adheres to cose.Signer
data := []byte("1234")
sig, _ := …
```
=> Add support for RS256, RS384, RS512 constants

algorithm.go, algorithm_test.go, headers.go, headers_test.go, key_test.go, signer.go, signer_test.go, verifier.go, verifier_test.go
This PR modifies the `Algorithm.String` message for values not defined in go-cose.
For example, when calling `Algorithm(7).String()`, it previously returned `unknown algorithm value 7`. Considering that other libraries can define their own algorithms, IMO that message is too verbose and seems more like an error than a useful name.
With the new behavior, the returned string will be `Algorithm(7)`.
While here, fix #164.
=> Improve Algorithm.String() message for unknown values

cbor.go, go.mod, go.sum, headers_test.go, sign_test.go
`fxamacker/cbor` release notes: https://github.com/fxamacker/cbor/releases/tag/v2.5.0.
Fixes #165
=> Upgrade fxamacker/cbor to v2.5.0

example_test.go
=> chore: fix duplicated import in the example

CODEOWNERS
Fix the syntax error as there should be an `@` before the usernames.
=> docs: fix the syntax of CODEOWNERS

.github/workflows/ci.yml, ecdsa_test.go, go.mod, key.go, key_test.go, verifier.go, verifier_test.go
Resolves #168, resolves #185.
Breaking changes:
- Remove compressed point support from EC2 keys
Other changes:
- Remove calls to deprecated functions in `crypto/elliptic`
- Upgrade golang to 1.21 for `crypto/ecdh`
Related:
- #178
=> refactor!: deprecate crypto elliptic

.vscode/settings.json, release-checklist.md, release-management.md, reports/README.md
=> Document the Release Process

cwt.go, cwt_test.go, headers.go
Due to DCO complications, this is a recreation of #183
Please see all comments in 183, including PR/LGTMs
fixes #173
fixes #184
=> Add support for CWT Claims & Type in Protected Headers

.gitignore, .vscode/settings.json, release-checklist.md, release-management.md
=> docs: update docs for release process 

.github/workflows/ci.yml
Fix #199 
- upgrade `codecov-action` to `v4`
- provide `CODECOV_TOKEN`
=> build: fix codecov

example_test.go
Add examples of signing and verifying with detached payload for #195
=> test: add examples for detached payload

release-checklist.md, release-management.md
When cutting [v1.3.0 release](https://github.com/veraison/go-cose/releases/tag/v1.3.0), there were several subtle differences in how we're actually doing a release.
- Split the voting and release steps into two sections
- Previous steps outlined creating a branch for future servicing. As opposed to creating a branch when actually needed, based on the commit of the serviced release.
=> Update Release Steps and Process

algorithm.go, cbor.go, countersign.go, ecdsa.go, ed25519.go, headers.go, key.go, rsa.go, sign.go, sign1.go, signer.go, verifier.go
Improves code documentation by
1. Better cross referencing in godoc
2. Fix typos
3. Align comment blocks to fit the line length of 80 characters
=> docs: improve code documentation

algorithm.go, key.go
Fix potential overflow when printing the error message of unknown values.
=> fix: fix overflow of unknown values

cwt_test.go
Fix #213 for the build failure of the CWT example.
=> fix(docs): fix build failure of the CWT example

README.md
This pull request updates the readme section describing custom algorithms, and provides an example test.
The current instructions in this section are not very helpful:
https://github.com/search?q=repo%3Averaison%2Fgo-cose%20RegisterAlgorithm&type=code
=> Update custom algorithms example

algorithm.go, algorithm_test.go, example_test.go, hash_envelope.go, hash_envelope_test.go, headers.go, headers_test.go
> [!IMPORTANT]
> This PR implements an RFC draft, which is "work in progress".
This PR implements the RFC draft [COSE Hash Envelope (draft-05)](https://www.ietf.org/archive/id/draft-ietf-cose-hash-envelope-05.html).
=> feat: cose hash envelope
